export const preset: WidgetConfig = {
  title: `Widget Window - ${Math.floor(Math.random() * 1000)}`,
  visible: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  creator: "Anonymous",
  path: "localhost:3000/",
  port: 3000,
  width: 300,
  height: 130,
  transparent: true,
  autoHideMenuBar: false,
  titleBarStyle: "hidden",
  resizable: true,
  maximizable: false,
  minimizable: false,
  skipTaskbar: true,
  thickFrame: false,
  frame: false,
  hasShadow: false,
  webpreferences: {
    contextIsolation: true,
    nodeIntegration: true,
  },
  closable: true,
  x: 10,
  y: 10,
};
